services:
  redis:
    image: redis:7-alpine
    container_name: light-gallery-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass 123456
    networks:
      - light-gallery-network

  postgres:
    image: postgres:16-alpine
    container_name: light-gallery-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: light-gallery
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - light-gallery-network

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local

networks:
  light-gallery-network:
    driver: bridge